### ISSUE TITLE
About the module

### ISSUE THREAD

**Issue by cagatayldzz** [HuntedHive/humhub-modules-registration#1]
1/ What is the exact function of the module ? 
2/ Is compatible with which version of Humhub
3/ How should be setup

**Comment by Censtudios** [comment]
I agree that it's really unclear what it does.

**Comment by Censtudios** [comment]
The owner keeps updating the module, but it's still not clear to anyone what the module does. People won't try it if they don't know it's function.

**Comment by nkeilar** [comment]
This is not an officially supported module. There is no intention to document or support it.
